<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Plugin\TwoFactorAuthCustomer42\Repository;

use Eccube\Repository\AbstractRepository;
use Doctrine\Persistence\ManagerRegistry;
use Plugin\TwoFactorAuthCustomer42\Entity\TwoFactorAuthConfig;

/**
 * TwoFactorAuthConfigRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwoFactorAuthConfigRepository extends AbstractRepository
{
    /**
     * TwoFactorAuthConfigRepository constructor.
     *
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, TwoFactorAuthConfig::class);
    }

    /**
     *
     * @return $result
     */
    public function findOne()
    {
        $qb = $this->createQueryBuilder('c')->setMaxResults(1)->select('c');

        // 実行
        $result = null;
        $results = $qb->getQuery()->getResult();
        if (!is_null($results) && count($results) > 0) {
            $result = $results[0];
        }

        return $result;
    }

}
